### ISSUE TITLE
Add ExportData to Twitter Tools List

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [nbats/FMHY#11]
I actively develop ExportData and it would be great to add it to the [Twitter Tools list](https://github.com/nbats/FMHY/wiki/%F0%9F%94%A7-Tools#-twitter-tools).

[ExportData](https://www.exportdata.io/) - Twitter Data Export Tool. 

It allows exporting an unlimited number of followers & followings, downloading historical tweets since 2006, and gathers trends in 467 locations.

**Comment by nbats** [comment]
Very cool thanks for adding
